### PR TITLE
Json to outputs: change input parameter to command_output

### PR DESCRIPTION
**Pull request by jochman**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
The `input` parameter is not clear. Changed with `command_output` and added better descriptions.

### CODE REVIEW

**Review by bakatzir — COMMENTED** [review]
I still think we should stay with the input/output convention, though better descs are needed.  @roysagi WDYT?

**Comment by roysagi** [comment]
@jochman - I agree with @bakatzir, let's keep the `input` convention. That being said we can improve the descriptions to include the phrasing "command output" for clarity.

**Comment by roysagi** [comment]
@jochman - do you want to fix this or should we close this PR?

**Comment by jochman** [comment]
> @jochman - do you want to fix this or should we close this PR?

I'll open a new pr

**Pull request closed without merging**
