### PR TITLE
Template name validation xsoar-linter

### PR DESCRIPTION
**Pull request by barchen1**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/36706

## Description
Added validation to xsoar-linter to make sure there are no script template names in `return_error` function.

## Screenshots
Screen Shot 2021-07-06 at 12 43 34

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by bakatzir** [comment]
The errors are on the lines:
`return_error(f'Failed to execute CBLiveGetFile_v2. Error: {str(e)}')`
can you explain the benefit? What am I missing here?

**Comment by barchen1** [comment]
@bakatzir I added a validation to make sure that the template names `BaseScript` and `HelloWorldScript` do not exist in the code.
You can take a look in the [issue ](https://github.com/demisto/etc/issues/36706)

**Review by guykeller — APPROVED** [review]
Please merge from Master + make sure UT pass

**Review by roysagi — APPROVED** [review]

**Comment by barchen1** [comment]
Closing this PR.
The issue will get fix in https://github.com/demisto/demisto-sdk/pull/1481

**Pull request closed without merging**
