### PR TITLE
Remove bandit

### PR DESCRIPTION
**Pull request by daryakoval**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
[fixes: link to the issue](https://jira-hq.paloaltonetworks.local/browse/CIAC-503)

## Description
Remove bandit from sdk

## Must have
- [ ] Tests
- [x] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

### CODE REVIEW

**Review by dantavori — APPROVED** [review]
nice, let's mention this in the changelog

**Comment by daryakoval** [comment]
> nice, let's mention this in the changelog
 
Of course, just thought that the release will be soon and didn't want to handle conflicts.. But I think I will merge it before the release.

**Review by dorschw — CHANGES_REQUESTED** [review]
Nice. This PR should only be merged after finishing the preceding subtasks (`[ ]` checkboxes) in the issue body.

**Comment by daryakoval** [comment]
> Nice. This PR should only be merged after finishing the preceding subtasks (`[ ]` checkboxes) in the issue body.

- first checkbox you told me that there is nothing to do with it. 
- regarding second checkbox, there are more than 20K alerts found, Should I  go over them all one by one to fix them? - @dantavori @ShahafBenYakir

**Pull request closed without merging**
