### PR TITLE
Separate Indicator And Incident Field

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/44362
fixes: https://github.com/demisto/etc/issues/43692

## Description
In the following PR:
1) I added a validation that given indicator field with type of HTML, the fromVersion is set to 6.1.0
2) I added a format that given an indicator field with type of HTML, format will format its fromVersion field to 6.1.0
3) I added a format that given an indicator field with type of GRID, format will format its fromVersion field to 5.5.0
4) Spliited the incident_field.py hook validation, that made validations of incident/indicator field to separate hooks.
5) Added a validation that selectValues do not contain empty types

Reason i combined two issues is because its working in same code which would cause bad conflicts, and the addition of selectValues is very minor.
## Screenshots
Paste here any images that will help the reviewer

## Must have
- [x] Tests
- [x] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

### CODE REVIEW

**Comment by tomneeman151293** [comment]
Test Failure To Indicate Bug (Validate)
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/13221/workflows/52a011d5-ba32-4eb0-bc79-9b6b4280f27e/jobs/71856

**Comment by tomneeman151293** [comment]
Format Test Failure Before Change
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/13223/workflows/196ac1e8-66f9-4dd1-b94f-68af7e03f81f/jobs/71874

**Comment by tomneeman151293** [comment]
test failure for selectValues empty
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/13258/workflows/94151635-4685-467a-a194-2b2eb33c8e81/jobs/72183

**Review by dantavori — APPROVED** [review]
amazing!

**Comment by idovandijk** [comment]
@ShahafBenYakir this caused ur PR to fail..
hopefully going forward I can catch these in advance

**Pull request merged**
