### PR TITLE
add from/to version to xsiam items schema

### PR DESCRIPTION
**Pull request by anara123**
## Related Issues
fixes: @nkanon please add the relevant ticket

## Description
Added from/to version to xsiam content items schema

### CODE REVIEW

**Review by dantavori — COMMENTED** [review]
is it going to be required? if so - need to specify this in the schemas and of course update the relevant content items accordingly.
in addition, need to add a default fromversion value in `FILETYPE_TO_DEFAULT_FROMVERSION` constant (the first supported versions of the types).

**Comment by anara123** [comment]
@dantavori I don't see a reason for this to be required

**Review by nkanon — COMMENTED** [review]
Hi @anara123,
I've began testing the fromVersion on content items.
For now, it looks like this filter mechanism is working as expected on dashboards.

Will update soon on the rest of the content items.

**Review by dantavori — APPROVED** [review]

**Review by dorschw — CHANGES_REQUESTED** [review]
We use `fromversion` for `yml` files, and `fromVersion` for `json`s. Please change accordingly.

**Comment by anara123** [comment]
> We use `fromversion` for `yml` files, and `fromVersion` for `json`s. Please change accordingly.

@dorschw I checked. it should be correct

**Pull request merged**
