### PR TITLE
fixed isArray in format

### PR DESCRIPTION
**Pull request by jochman**
## Status
- [x] In Progress
- [ ] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/30208

## Description
New behavior:
If a command has already contained isArray and it's True: will preserve
if it's false: will preserve and print a warning
if there are no arguments: Will auto-add with a print.

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by Itay4** [comment]
please add test

**Comment by jochman** [comment]
> please add test and update changelog

Already covered 
image

**Comment by Itay4** [comment]
do we have test that it is false before format and stays that way after ?

**Comment by jochman** [comment]
> do we have test that it is false before format and stays that way after ?

Yes.

**Comment by jochman** [comment]
@Itay4 see test_isarray_false.
I've contained all the unittests in a class for better performance (pytest execute classes parallel)

**Review by Itay4 — APPROVED** [review]

**Review by Itay4 — CHANGES_REQUESTED** [review]
update changelog

**Comment by Itay4** [comment]
seems like your changelog is synced with master
also change it to something like:
`* The **format** command will now preserve the *isArray* argument in integratio reputation command and display a warning in case it is set to ***false***.`

**Review by Itay4 — APPROVED** [review]

**Pull request merged**
