### PR TITLE
default `keep_order=False`

### PR DESCRIPTION
**Pull request by rshunim**
Speeding up `yaml.load` up to 4x if we don’t need them ordered.
We only need them ordered in one place in format - where it's now `keep_order=True`.

### CODE REVIEW

**Review by dorschw — APPROVED** [review]

**Comment by rshunim** [comment]
Second [Nightly](https://code.pan.run/xsoar/content/-/pipelines/5811386)

**Comment by rshunim** [comment]
Link to [Nightly](https://code.pan.run/xsoar/content/-/pipelines/5820027)
(After pull from master)

**Review by dorschw — APPROVED** [review]
Please fix the changelog before merging

**Comment by rshunim** [comment]
Link to [nightly](https://code.pan.run/xsoar/content/-/pipelines/6240137)

**Comment by rshunim** [comment]
Link to [nightly](https://code.pan.run/xsoar/content/-/pipelines/6301007)

**Pull request merged**
