### PR TITLE
add validation for feedTags key in integration yml

### PR DESCRIPTION
**Pull request by orhovy**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/25719

## Description
Added validation of Tag param in feed integrations.

## Must have
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by orhovy** [comment]
I ran it with content using validate all, tried to check it with nightly trigger build, but validate does not run on nightly any more. there are some feeds that did not implement the tags param yet
Also there are some that do not have the exact additionalinfo , I am working on that in those pr and will open a few more:
https://github.com/demisto/content/pull/8284
https://github.com/demisto/content/pull/8281

**Comment by bakatzir** [comment]
@orhovy Print screen or comment with a link to a validate run on all content that passes so we can merge this PR.

**Comment by orhovy** [comment]
> @orhovy Print screen or comment with a link to a validate run on all content that passes so we can merge this PR.

Last Pr after running validate -a
https://github.com/demisto/content/pull/8352

**Comment by orhovy** [comment]
image
can I merge?

**Comment by bakatzir** [comment]
Yes @orhovy

**Comment by bakatzir** [comment]
fixes: https://github.com/demisto/etc/issues/23078

**Pull request merged**
