### PR TITLE
Fix format contributors

### PR DESCRIPTION
**Pull request by MosheEichler**
fixes: https://github.com/demisto/etc/issues/42299

## Related PR's
https://github.com/demisto/demisto-sdk/pull/1360

## Description
Fix the contributors format to run on all files added/modified/renamed

## Screenshots
Paste here any images that will help the reviewer

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [ ] N/A - Functionality cannot be implemented in the extension because <u>\<add-reason-here\></u>

### CODE REVIEW

**Comment by MosheEichler** [comment]
[lint to the PR with the demisto-sdk:Fix format contributors](https://github.com/demisto/content/pull/15735)
[build-flow](https://github.com/demisto/contribution-management/runs/4178223552?check_suite_focus=true)

[lint to the PR with the demisto-sdk:master](https://github.com/demisto/content/pull/15736)
[build-flow](https://github.com/demisto/contribution-management/runs/4178310307?check_suite_focus=true)

**Comment by barchen1** [comment]
@MosheEichler Please make sure to test your fix:
1. contribute to an existing pack
2. Contribute to a new pack
3. Resubmit

Let me know if you need my help.

**Comment by tomneeman151293** [comment]
Can the bug scenario be tested via unit test?
- If not, why not?
If it can be
- Please comment your fix. Add test or tests to indicate the bug. See the test fails with the expected error that format was not as expected
- Uncomment your fix, then see test passes

**Comment by MosheEichler** [comment]
@barchen1 @tomneeman151293  I added tests for new and existing packs (re-submit is the same as the existing pack)

**Review by tomneeman151293 — APPROVED** [review]

**Pull request merged**
