### PR TITLE
added hiddenuser to schema for integration

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Status
- [] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
Link will be added later

## Description
After an enhancement on server, being able to hide the username from credentials, and having password visible only by adding a tag of hiddenusername:true to the credentials param, demisto-sdk validate fails because it does not belong to the schema.

Added the hiddenusername to the schema to solve this issue.

## Screenshots

Screen Shot 2021-03-03 at 17 49 13
Screen Shot 2021-03-03 at 18 12 06

### CODE REVIEW

**Comment by roysagi** [comment]
@tomneeman151293 - Please make sure your integration passes validation with this addition.

**Review by ShahafBenYakir — COMMENTED** [review]
Let's make sure this appear in one of the schemas unit-tests 
Also need to list it in the changelog.md file

**Comment by tomneeman151293** [comment]
@ShahafBenYakir Added a link for the test failure without hiddenusername added to schema
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/8454/workflows/e7096ee6-1ba5-4e9a-9edf-21f97a4da2bd/jobs/34246

**Comment by ShahafBenYakir** [comment]
@tomneeman151293 I don't see the same error [here](https://github.com/demisto/demisto-sdk/pull/1152#issuecomment-790727598) as the one described in the PR body, can we make the test fail exactly on the relevant error of field does not exist in scheme?

**Comment by tomneeman151293** [comment]
@ShahafBenYakir 
The test failure shows it is ST-110, but it doesn't show full error,
When i run it locally, it shows me what was logged

When i comment the hiddenusername from schema i get
Screen Shot 2021-03-07 at 14 31 40
when i uncomment it
Screen Shot 2021-03-07 at 14 33 06

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
