### PR TITLE
added repleacment for boundary

### PR DESCRIPTION
**Pull request by esharf**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/31779

## Description
added a replacement to the random boundary.

## Screenshots
Screen Shot 2021-05-19 at 16 12 46

## Must have
- [x] Tests

### CODE REVIEW

**Comment by esharf** [comment]
@avidan-H we should create a new AMI to test on live before merging it.
FYI @yaakovi
Afterward, we can merge https://github.com/demisto/content/pull/12756.

**Comment by avidan-H** [comment]
> @avidan-H we should create a new AMI to test on live before merging it.
> FYI @yaakovi
> Afterward, we can merge [demisto/content#12756](https://github.com/demisto/content/pull/12756).

@esharf I'm not sure we need a new AMI. I think you might be able to push a branch to `content` repo updating the python3 requirements file to use the `demisto-sdk` version from your branch here and trigger a build against that branch in `content`.

**Comment by esharf** [comment]
> > @avidan-H we should create a new AMI to test on live before merging it.
> > FYI @yaakovi
> > Afterward, we can merge [demisto/content#12756](https://github.com/demisto/content/pull/12756).
> 
> @esharf I'm not sure we need a new AMI. I think you might be able to push a branch to `content` repo updating the python3 requirements file to use the `demisto-sdk` version from your branch here and trigger a build against that branch in `content`.

@avidan-H i don’t think this will help because it looks that the file is placed there and it’s a part of the demisto-sdk installation.

**Comment by avidan-H** [comment]
> @avidan-H i don’t think this will help because it looks that the file is placed there and it’s a part of the demisto-sdk installation.

Where do you see that? I think we install the `demisto-sdk` as a dev dependency during the build and use it.

**Review by yaakovi — COMMENTED** [review]
looks good to me.
@esharf please set a short call with me and @avidan-H about how to test it before merging

**Comment by esharf** [comment]
@yaakovi i already talked with @avidan-H and we found that we don’t need to do anything except running the build with a custom SDK version.
will handle it in https://github.com/demisto/content/pull/12756

**Comment by esharf** [comment]
@yaakovi it’s already in testing in this [build](https://app.circleci.com/pipelines/github/demisto/content/87475/workflows/963d7fad-9bdd-4250-aeb7-07c84135b2ab).

**Review by yaakovi — APPROVED** [review]

**Pull request merged**
