### PR TITLE
Verify Community/Partner text does not appear where it shouldn't

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/33261

## Description
Added validation for names not containing contribution type name.
Also added a small optimization to pack unique files to open metadata file only one and not every time

## Must have
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by tomneeman151293** [comment]
test failure example
https://app.circleci.com/pipelines/github/demisto/demisto-sdk/10807/workflows/e2919bfc-426a-4a6a-8fbf-acf0f8659637/jobs/52067

**Comment by tomneeman151293** [comment]
@dantavori I think this is ready for PR now. If you could pay close attention to the error codes as i am not sure i followed the standards

**Comment by tomneeman151293** [comment]
@dantavori ready for review

**Review by dantavori — CHANGES_REQUESTED** [review]
great work, last touches and we can merge 💪🏽 
also don't forget to open a pull request in content repo for the ignored errors.

**Comment by tomneeman151293** [comment]
@dantavori Ready for PR

**Review by dantavori — APPROVED** [review]
fix the failing checks and you can merge 🏆

**Pull request merged**
