### PR TITLE
make generate-unit-tests as an extra dependency

### PR DESCRIPTION
**Pull request by ilaner**
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-9185

This will make the `generate-unit-test` command to work only if demisto-sdk is installed with `pip install demisto-sdk[generate-unit-tests].

### CODE REVIEW

**Review by GuyAfik — APPROVED** [review]
good job! 💯

**Review by yuvalbenshalom — APPROVED** [review]

**Comment by GuyAfik** [comment]
@ilaner this should be documented with @tschanfeld

**Comment by tschanfeld** [comment]
@ilaner Should this be a note 'The generate-unit-test command only works if demisto-sdk is installed with `pip install demisto-sdk [generate-unit-tests].'
That would be at the top - https://docs-cortex.paloaltonetworks.com/r/1/Demisto-SDK-Guide/generate-unit-tests

should the default commands here - https://docs-cortex.paloaltonetworks.com/r/1/Demisto-SDK-Guide/Install-Demisto-SDK be changed? do we expect most people to want to have this command available?
pip3 install --upgrade demisto-sdk  changed to - pip3 install --upgrade demisto-sdk [generate-unit-tests]
pip3 install demisto-sdk changed to - pip3 install demisto-sdk [generate-unit-tests]

**Comment by tschanfeld** [comment]
@ilaner ?

**Comment by tschanfeld** [comment]
Per @ilaner I am putting note only in generate-unit-tests topic 'The generate-unit-test command only works if demisto-sdk is installed with ​pip install demisto-sdk [generate-unit-tests]​​.'

Please confirm I can publish.

**Pull request merged**
