### PR TITLE
added enhancements for base integration

### PR DESCRIPTION
**Pull request by tomneeman151293**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Description
* Added at start of main function one call to demisto.params(), and changed all calls in main from demisto.params() to params
* Added at start of main function one call to demisto.args(), and changed all calls in main from demisto.args() to args
* Added at start of main function one call to demisto.command(), and changed all calls in main from demisto.command() to command

* Added else clause containing NotImplementedError

## Must have
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by tomneeman151293** [comment]
@ShahafBenYakir  Let me know if you think this change requires CHANGELOG/tests. If so I will add

**Review by bakatzir — COMMENTED** [review]
Not sure if in the scope but I suggest adding:
- reputation command ex (ip/file/domain) with the `indicator` and `dbotscore` classes.
- generic fetching - with explanations on the last update time and demisto.incidents()

**Comment by ShahafBenYakir** [comment]
@tomneeman151293 No need for tests, you will however need to add RN

@bakatzir Sounds important, lets open a dedicated issue for relevant stuff we want to update in the base integration (as you suggested it is indeed out of the scope of this).
Need to make sure we are not mixing between this and hello world.

**Review by ShahafBenYakir — APPROVED** [review]

**Comment by tomneeman151293** [comment]
closing this pr as it have not been merged and i have seen @jochman have done similar changes

**Pull request closed without merging**
