### PR TITLE
fix docker image pulling for pwsh in linter

### PR DESCRIPTION
**Pull request by bakatzir**
## Status
- [x] Ready

## Description
see cert in docker in the referenced issue

## Related Issues
fixes: https://github.com/demisto/etc/issues/25468

### CODE REVIEW

**Comment by glicht** [comment]
@bakatzir is this ready or a draft?

**Comment by bakatzir** [comment]
@glicht I want to try and figure if I can create a unit/integration test for this flow. but it is working as expected and fixes the issue.

**Review by glicht — APPROVED** [review]
please try doing a manual test. not sure that creating an integration test is worth the effort.

**Comment by bakatzir** [comment]
@glicht validated, commented in the referenced issue.

**Pull request merged**
