### PR TITLE
Add pyupgrade to pre commit hooks

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

## Description
Added 2 pre-commit hooks:
1. black - we have inconsistent code style in the repo cause of refactoring done in a few iterations, need `black` to try and align to one style
2. pyupgrade - we still have some leftovers of python 2 syntax in the code, need `pyupgrade` to update those to python 3

### CODE REVIEW

**Comment by glicht** [comment]
@Itay4 I think we should exclude the test files. Looking at the build I see the hooks are running also on test files.

**Comment by Itay4** [comment]
@glicht i've removed `black` as it doesn't run well with `flake8` and `autopep8`

**Comment by glicht** [comment]
So, if you've removed `black` do we need all the formatting changes you've done?

**Comment by Itay4** [comment]
@glicht done

**Pull request merged**
