### PR TITLE
Validate approved tags and usecases

### PR DESCRIPTION
**Pull request by Itay4**
## Status
- [x] Ready

## Related Issues
fixes: https://github.com/demisto/etc/issues/30007

## Description
Added validation for approved tags and usecases
Still need to clean non-approved tags and usecases from the content repo

## Must have
- [x] Tests

### CODE REVIEW

**Comment by Itay4** [comment]
see validation failure in https://app.circleci.com/pipelines/github/demisto/demisto-sdk/6313/workflows/6d91873c-eb64-4a04-b188-5e12bfc3bbfc/jobs/17280/parallel-runs/0/steps/0-103

**Review by glicht — COMMENTED** [review]
I think the files: `approved_*.json`  should be taken from the Content repo same as we use demisto_mock for linting. That way in the same PR that there is a new pack that needs a new tag it is all done together.

**Comment by Itay4** [comment]
opened content PR - https://github.com/demisto/content/pull/9780

**Comment by randomhash** [comment]
@glicht Hello, sorry for disturbing by offtop once more, please release a new version after merge https://github.com/functionalone/serverless-iam-roles-per-function/issues/57

**Review by yaakovi — APPROVED** [review]

**Comment by yaakovi** [comment]
@Itay4 build is failing on new unit tests

**Comment by Itay4** [comment]
> @Itay4 build is failing on new unit tests

yea need to merge the content pr

**Pull request merged**
