### PR TITLE
Secrets path not found - fixed the issue + UT

### PR DESCRIPTION
**Pull request by teizenman**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/25250

## Description
The issue occurred when the file name had a space in it.

## Must have
- [X] Tests

### CODE REVIEW

**Comment by teizenman** [comment]
@roysagi RN please

**Comment by ronykoz** [comment]
@teizenman run on this branch https://github.com/demisto/content/pull/7039/files using the trigger script i want to make sure it solves this because i don't think the file name had space

**Comment by teizenman** [comment]
I tested it locally of course, but also: https://circleci.com/gh/demisto/demisto-sdk/4082

**Comment by roysagi** [comment]
@teizenman - you are good to go

**Pull request merged**
