### PR TITLE
SDK Readme Updates

### PR DESCRIPTION
**Pull request by Shellyber**
## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-11880

## Description
- Updated the main README for the demisto-sdk
- Updated some of the helper arguments for the commands in main 
- Updated READMEs according to the helper

### CODE REVIEW

**Comment by Shellyber** [comment]
@samuelFain @dorschw anything more we want to add here at the moment?

**Comment by ShahafBenYakir** [comment]
@Shellyber I think we said we want to align the -help feature with these docs as well no?

**Comment by samuelFain** [comment]
> @samuelFain @dorschw anything more we want to add here at the moment?

@Shellyber 
I think it looks a lot better, the separation between of the installation and environment setup is very clear.
About `docs/demisto-sdk-docker.md`, is it corresponding with a page in the documentation as well? Do we plan to add more markdowns to the docs folder?

**Comment by Shellyber** [comment]
> @Shellyber I think we said we want to align the -help feature with these docs as well no?

Yes. I'll add the demisto-sdk flags as well to the docs here and afterward to the official docs site as well.

**Comment by Shellyber** [comment]
> > @samuelFain @dorschw anything more we want to add here at the moment?
> 
> @Shellyber I think it looks a lot better, the separation between of the installation and environment setup is very clear. About `docs/demisto-sdk-docker.md`, is it corresponding with a page in the documentation as well? Do we plan to add more markdowns to the docs folder?

For the moment, the docker article does not exist on the official docs site - right now it is referred to xsoar.pan.dev page which won't be longer accessible. So I'm adding it here in the meantime. 
Once I'll do the work with the docs team, we can add the article directly there, and reference from here. 
But I think it is a good place to keep this article as well. 
Regarding more docs, not at the moment, but it is good to have it anyway.

**Comment by Shellyber** [comment]
@samuelFain @ShahafBenYakir If you can review

**Review by ShahafBenYakir — APPROVED** [review]

**Pull request merged**
