### PR TITLE
Fix unified yml creation

### PR DESCRIPTION
**Pull request by liorblob**
## Status
- [ ] In Progress
- [X] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: https://github.com/demisto/etc/issues/24091

Create a copy of the yml before altering it

### CODE REVIEW

**Comment by Itay4** [comment]
looks ok
lets add test and update changelog

**Comment by yuvalbenshalom** [comment]
@Itay4 note that we will probably need to release this tomorrow because this blocks moving some unified integrations.

**Comment by yuvalbenshalom** [comment]
@liorblob is this ready to merge?

**Comment by liorblob** [comment]
@yuvalbenshalom I'll run my build with this branch and then merge

**Pull request merged**
