### PR TITLE
Make lint container name unique

### PR DESCRIPTION
**Pull request by DinaMeylakh**
## Related Issues
fixes: https://jira-dc.paloaltonetworks.com/browse/CIAC-6015

## Description
Lint container names are not unique per image, this causes errors when running lint in parallel on a few different images (like we do with the native image and its candidates). In this PR I make the docker container name include the image name and therefore make it unique per image.

### CODE REVIEW

**Comment by DinaMeylakh** [comment]
TDD: failing unittests [job](https://app.circleci.com/pipelines/github/demisto/demisto-sdk/29163/workflows/77eef26b-e97d-4210-a12b-5a79152cc861/jobs/262004) in commit [256cbc3](https://github.com/demisto/demisto-sdk/pull/3750/commits/256cbc341e98e53bc73402fcd540d06e00266fdb)

**Review by ShahafBenYakir — APPROVED** [review]
Looks good on my end

**Comment by ShahafBenYakir** [comment]
@JudahSchwartz can you have a quick look here?

**Review by JudahSchwartz — APPROVED** [review]
makes sense, nice!

**Pull request merged**
