### PR TITLE
Fix to run isort after autopep8

### PR DESCRIPTION
**Pull request by maxgubler**
## Status
- [ ] In Progress
- [x] Ready
- [ ] In Hold - (Reason for hold)

## Related Issues
fixes: #2423

## Description
isort was not being run on download because it was subject to the value of `self.pipenv` which was always `False`. This moves the running of isort outside that code block and runs it immediately after autopep8.

## Must have
- [ ] Tests
- [ ] Documentation
- [ ] [VS Code Extension](https://docs.gitlab.com/ee/ci/yaml/#tags)
  - [ ] Functionality implemented in the extension - <u>\<link-to-pr-here\></u>
  - [x] N/A - Irrelevant

### CODE REVIEW

**Review by dorschw — APPROVED** [review]

**Comment by maxgubler** [comment]
@dorschw Is there anything additional you need from me on this? Also, I see this changelog entry* which you added does not reflect the issue correctly (also download is misspelled): Please note that this pull request fixes the fact that isort _will **never** run_.

> *[`Fixed an issue where **dowlnoad** would not properly handle a missing installation of `isort`, now showing a proper message.`](https://github.com/demisto/demisto-sdk/blob/ae7c250fba9e268c8e6ad3090a3731d883840fc9/CHANGELOG.md?plain=1#L7)

**Comment by dorschw** [comment]
Hi, sorry for the delay, feel free to correct the changelog, then I'll merge it. 
The next release is scheduled for tomorrow, so merging it in the next hours will make it into 1.7.8.

**Comment by maxgubler** [comment]
@dorschw -- done.

**Comment by maxgubler** [comment]
@dorschw Just noticed I had modified the changelog line you originally had under 1.7.7 -- I'm assuming you want that moved under Unreleased instead? Do you want to do that or shall I?

**Pull request merged**
